[DO-308]  access point 리소스 생성 기능 추가
inflearn/terraform-aws-efs pull request #1
Opened 2022-06-24 09:52 UTC by xteen16

+ aws_efs_access_point 생성 기능 추가
+ `{dir_path = access_point_id}` output 추가

2022-06-24 09:54 UTC, wbqd approved these changes

2022-07-01 07:43 UTC, devsunb requested changes

2022-07-01 07:43 UTC, devsunb commented on variables.tf
> +variable "access_point" {
리스트를 받으니 변수명으로 access_points 가 어떨까요!

2022-07-01 09:23 UTC, xteen16 commented on variables.tf
> +variable "access_point" {
@devsunb  수정했습니다

2022-07-04 04:07 UTC, devsunb approved these changes

2022-07-04 04:14 UTC, jakeinflab approved these changes

2022-07-04 04:16 UTC, merged